---
- name: install fail2ban packages
  apt: pkg={{ item }} state=present
  with_items:
    - fail2ban

- name: create fail2ban configuration
  copy: >
    src=fail2ban.conf dest=/etc/fail2ban/fail2ban.conf
    owner=root group=root mode=0644
  notify:
    - restart fail2ban

- name: create fail2ban jail configuration
  copy: >
    src=jail.conf dest=/etc/fail2ban/jail.conf
    owner=root group=root mode=0644
  notify:
    - restart fail2ban

- name: ensure fail2ban is running
  service: name=fail2ban state=running enabled=yes
